CREATE TABLE USER (
  USER_ID   INT          NOT NULL AUTO_INCREMENT,
  USERNAME  VARCHAR(255) NOT NULL,
  LASTNAME  VARCHAR(255) NOT NULL,
  FIRSTNAME VARCHAR(255),
  PASSWORD  VARCHAR(100) NOT NULL,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE LOGGED_USER (
  USER_ID     INT          NOT NULL,
  AUTHKEY     VARCHAR(160) NOT NULL,
  LOGGED_TIME TIMESTAMP,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE DEVICE (
  DEVICE_ID   INT          NOT NULL AUTO_INCREMENT,
  DEVICE_KEY  VARCHAR(160) NOT NULL,
  IS_ACTIVE   CHAR,
  DESCTIPTION VARCHAR(4000),
  PRIMARY KEY (DEVICE_ID)
);

INSERT INTO DEVICE (DEVICE_KEY, IS_ACTIVE,DESCTIPTION.)
VALUES ("LIVING_ROOM", '0', "Living room light");